List<String> asciiArtArchLinux = [
  "                   -`",
  "                  .o+`",
  "                 `ooo/",
  "                `+oooo:",
  "               `+oooooo:",
  "               -+oooooo+:",
  "             `/:-:++oooo+:",
  "            `/++++/+++++++:",
  "           `/++++++++++++++:",
  "          `/+++ooooooooooooo/`",
  "         ./ooosssso++osssssso+`",
  "        .oossssso-````/ossssss+`",
  "       -osssssso.      :ssssssso.",
  "      :osssssss/        osssso+++.",
  "     /ossssssss/        +ssssooo/-",
  "   `/ossssso+/:-        -:/+osssso+-",
  "  `+sso+:-`                 `.-/+oso:",
  " `++:.                           `-/+/",
  " .`                                 `",
]
    .map((string) => string.replaceAll(' ', ' '))
    .toList(); // there is a hidden character^ here

List<String> asciiArtEndeavour = [
  "..............................",
  "................:+:...........",
  "..............,+?%%+,.........",
  "............,:*%%%%%?;,.......",
  "...........:+?%%%%%%%%*:......",
  ".........,;*?%%%%%%%%%%?+,....",
  ".......,;+*%%%%%%%%%%%%%?*:...",
  "......:++?%%%%%%%%%%%%%%%?*;..",
  "....,;++?%%%%%%%%%%%%%%%%%**;.",
  "..,:++*?%%%%%%%%%%%%%%%%%%?**;",
  ",:+++*%%%%%%%%%%%%%%%%%%%%?***",
  ":;;;*?%%%%%%%%%%%%%%%%%%%?***+",
  "..,+*********??????????****+;,",
  "..:;;;;;;;;;;;;;;;;;::::,,,...",
  "..............................",
];

List<String> asciiArtManjaro = [
  ":::::::::::::::::::. '::::::::",
  ":::::::::::::::::::. '::::::::",
  ":::::::::::::::::::. '::::::::",
  ":::::::::::::::::::. '::::::::",
  "::::::::`..........  '::::::::",
  "::::::::'  ````````  '::::::::",
  "::::::::' .::::::::. '::::::::",
  "::::::::' .::::::::. '::::::::",
  "::::::::' .::::::::. '::::::::",
  "::::::::' .::::::::. '::::::::",
  "::::::::' .::::::::. '::::::::",
  "::::::::' .::::::::. '::::::::",
  "::::::::' .::::::::. '::::::::",
  "::::::::' .::::::::. '::::::::",
  "::::::::' .::::::::. '::::::::",
].map((string) => string.replaceAll(' ', ' ')).toList();

List<String> asciiArtOpensuse = [
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
  "uuuuuuuun/1]_+_?[)fu-)juuuuuuu",
  "uuuuuut+;::::::::::;::>-/uuuuu",
  "uuuuu1:]({1[;::::::::I+_-uuuuu",
  "uuuuu~>u!t(<r!:+_+;!(1)/nuuuuu",
  "uuuuuj><}{~~ux1(xur1\\uuuuuuuuu",
  "uuuuuuur\\\\juuuuuuuuuuuuuuuuuuu",
  "uuuuu{i~<u]1u1[u<~>1u~~~1uuuuu",
  "uuuuu<;!~u;<u~Iu,!l1u`~~juuuuu",
  "uuuuu?<~\"n(,~,(ui~\\!iu:~~1uuuuu",
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
  "",
];

List<String> asciiArtUbuntu = [
  "                              ",
  "                              ",
  "                  :+*=        ",
  "           :=++++:=##+        ",
  "        :++.=+===*+==:        ",
  "       =##+.      .=##=       ",
  "   .--.*#=          -##-      ",
  "   *##+:#.           --:      ",
  "   .--.*#=          -##-      ",
  "       =##=.      .=##=       ",
  "        :**.=====*+==:        ",
  "           :=++++-=*#+        ",
  "                  -**=        ",
  "                              ",
  "                              ",
  "",
].map((string) => string.replaceAll(' ', ' ')).toList();

List<List<String>> asciiArts = [
  asciiArtArchLinux,
  asciiArtEndeavour,
  asciiArtManjaro,
  asciiArtOpensuse,
  asciiArtUbuntu,
];
