List<List<String>> distroSpecs = [
  // Arch Linux
  [
    "user@user",
    "---------",
    "OS: Arch LInux x86_64",
    "Host: Zephyrus G14 Gaming Laptop",
    "Kernel: Linux 5.15.0-arch1-1",
    "Uptime: 3 days, 2 hours, 12 minutes",
    "Packages: 2045 (pacman)",
    "Shell: bash 5.2.26",
    "Resolution: 1920x1080 ",
    "DE: Plasma 5.27.11",
    "WM: KWin",
    "Theme: Breath Light [Plasma], Flat-Remix-GTK-Blue-Light-Solid [GTK2/3]",
    "Icons: Tela-circle-dark [GTK2/3]",
    "Terminal Font: agave Nerd Font Mono 14",
    "Terminal: konsole",
    "CPU: AMD Ryzen 9 5900X (24) @ 3.70GHz",
    "GPU: NVIDIA GeForce RTX 3090",
    "Memory: 32GB DDR4 RAM @ 3600MHz",
    "Storage: 2TB NVMe SSD",
  ],
// endeavouros
  [
    "user@user",
    "---------",
    "OS: EndeavourOS x86_64",
    "Host: Zephyrus G14 Gaming Laptop",
    "Kernel: Linux 5.15.0-arch1-1",
    "Uptime: 3 days, 2 hours, 12 minutes",
    "Packages: 2045 (pacman)",
    "Shell: bash 5.2.26",
    "Resolution: 1920x1080 ",
    "DE: Plasma 5.27.11",
    "WM: KWin",
    "Theme: Breath Light [Plasma], Flat-Remix-GTK-Blue-Light-Solid [GTK2/3]",
    "Icons: Tela-circle-dark [GTK2/3]",
    "Terminal Font: agave Nerd Font Mono 14",
    "Terminal: konsole",
    "CPU: AMD Ryzen 9 5900X (24) @ 3.70GHz",
    "GPU: NVIDIA GeForce RTX 3090",
    "Memory: 32GB DDR4 RAM @ 3600MHz",
    "Storage: 2TB NVMe SSD",
  ],
// Manjaro
  [
    "user@user",
    "---------",
    "OS: Manjaro Linux x86_64",
    "Host: Zephyrus G14 Gaming Laptop",
    "Kernel: Linux 5.15.150-1-MANJARO",
    "Uptime: 3 days, 2 hours, 12 minutes",
    "Packages: 2045 (pacman)",
    "Shell: bash 5.2.26",
    "Resolution: 1920x1080 ",
    "DE: Plasma 5.27.11",
    "WM: KWin",
    "Theme: Breath Light [Plasma], Flat-Remix-GTK-Blue-Light-Solid [GTK2/3]",
    "Icons: Tela-circle-dark [GTK2/3]",
    "Terminal Font: agave Nerd Font Mono 14",
    "Terminal: konsole",
    "CPU: AMD Ryzen 9 5900X (24) @ 3.70GHz",
    "GPU: NVIDIA GeForce RTX 3090",
    "Memory: 32GB DDR4 RAM @ 3600MHz",
    "Storage: 2TB NVMe SSD",
  ],
// Opensuse
  [
    "user@user",
    "---------",
    "OS: openSUSE Leap x86_64",
    "Host: Zephyrus G14 Gaming Laptop",
    "Kernel: Linux 5.15.0-1-default",
    "Uptime: 3 days, 2 hours, 12 minutes",
    "Packages: 2045 (zypper)",
    "Shell: bash 5.2.26",
    "Resolution: 1920x1080 ",
    "DE: Plasma 5.27.11",
    "WM: KWin",
    "Theme: Breath Light [Plasma], Flat-Remix-GTK-Blue-Light-Solid [GTK2/3]",
    "Icons: Tela-circle-dark [GTK2/3]",
    "Terminal Font: agave Nerd Font Mono 14",
    "Terminal: konsole",
    "CPU: AMD Ryzen 9 5900X (24) @ 3.70GHz",
    "GPU: NVIDIA GeForce RTX 3090",
    "Memory: 32GB DDR4 RAM @ 3600MHz",
    "Storage: 2TB NVMe SSD",
  ],
// Ubuntu
  [
    "user@user",
    "---------",
    "OS: Ubuntu 22.04 LTS x86_64",
    "Host: Zephyrus G14 Gaming Laptop",
    "Kernel: Linux 5.15.0-ubuntu2-generic",
    "Uptime: 3 days, 2 hours, 12 minutes",
    "Packages: 2045 (apt)",
    "Shell: bash 5.2.26",
    "Resolution: 1920x1080 ",
    "DE: Plasma 5.27.11",
    "WM: KWin",
    "Theme: Breath Light [Plasma], Flat-Remix-GTK-Blue-Light-Solid [GTK2/3]",
    "Icons: Tela-circle-dark [GTK2/3]",
    "Terminal Font: agave Nerd Font Mono 14",
    "Terminal: konsole",
    "CPU: AMD Ryzen 9 5900X (24) @ 3.70GHz",
    "GPU: NVIDIA GeForce RTX 3090",
    "Memory: 32GB DDR4 RAM @ 3600MHz",
    "Storage: 2TB NVMe SSD",
  ]
];
//List<String> specsArchLinux 

//List<String> specsManjaro = ;

//List<String> specsOpenSUSE = ;

//List<String> specsUbuntu = ;

//List<String> specsEndeavourOS = ;
